project:
  type: website

website:
  title: "" 
  description: ""
  navbar:
    title: "Ana Bodevan"
    left:
      - text: Blog
        href: index.qmd
      - text: About
        href: about.qmd 
    tools:
      - icon: github
        href: https://github.com/pabsantos/homepage
      - icon: linkedin
        href: https://www.linkedin.com/in/ana-luisa-bodevan-979388207/
      - icon: envelope
        href: mailto::anabodevan01@gmail.com
    background: "white"
    foreground: "black"
  page-footer:
    left:
      - href: https://www.quarto.org
        text: Built with ❤️ & Quarto
format:
  html:
    theme: [sandstone, style.css]
    highlight-style: github
    toc: false
    backgroundcolor: "white"
    fontcolor: "black"
    linkcolor: "black"
